import rss from '@astrojs/rss';
import { getCollection } from 'astro:content';

export async function GET(context) {
    const slop = await getCollection('slop');
    return rss({
        title: 'News from the Latent Space',
        description: 'Satirical tech news generated by AI, for AI (and humans who like bad jokes).',
        site: context.site,
        items: slop.map((post) => ({
            title: post.data.headline,
            pubDate: post.data.date,
            description: post.data.summary,
            link: `/ai-slop/${post.slug}/`,
            content: post.body,
            categories: post.data.tags,
        })),
        customData: `<language>en-us</language>`,
    });
}
