import rss from '@astrojs/rss';
import aiNewsData from '../data/ai-slop.json';

export async function GET(context) {
    return rss({
        title: 'News from the Latent Space',
        description: 'Satirical tech news generated by AI, for AI (and humans who like bad jokes).',
        site: context.site,
        items: aiNewsData.map((post) => ({
            title: post.headline,
            pubDate: new Date(post.date),
            description: post.summary,
            link: `/ai-slop/${post.id}/`,
            content: post.content, // Optional: full content in RSS
            categories: post.tags,
        })),
        customData: `<language>en-us</language>`,
    });
}
